# Generated by Django 4.2.1 on 2023-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
    ]
