# Generated by Django 4.2.1 on 2023-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MetodosDePago', models.CharField(max_length=100)),
            ],
        ),
    ]
