# Generated by Django 4.2.1 on 2023-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crudProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
                ('linkImagen', models.URLField()),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
