# Generated by Django 4.2.2 on 2023-06-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotarApp', '0002_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
