# Generated by Django 4.2.2 on 2023-06-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotarApp', '0003_alter_usuario_options_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
